/**
 * strategy-review.ts
 * Department of Strategy — Swarm OS v4.2
 *
 * Lê growth-actions.json gerado pelo Flow Intelligence,
 * submete ao board (Ray Dalio · Goldratt · Porter),
 * e produz approved-actions.json pronto para execução.
 *
 * Uso: npx tsx scripts/strategy-review.ts --project={projectId}
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import {
  createAgentSession,
  SessionManager,
  AuthStorage,
  ModelRegistry,
} from "@mariozechner/pi-coding-agent";

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// ─── Config ─────────────────────────────────────────────────────────────────

const cliArgs   = process.argv.slice(2);
const projectArg = cliArgs.find((a) => a.startsWith("--project="));
const PROJECT_ID = projectArg ? projectArg.split("=")[1] : "one-agent-corp";

const ROOT       = path.resolve(__dirname, "..");
const WORKSPACE  = path.join(ROOT, "workspace", PROJECT_ID === "one-agent-corp" ? "" : PROJECT_ID);
const FLOW_DIR   = path.join(WORKSPACE, "flow");
const MINDS_DIR  = "C:/Users/Administrador/.claude/minds";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function readText(p: string): string {
  try { return fs.readFileSync(p, "utf-8"); }
  catch { return ""; }
}

function readJson<T>(p: string): T | null {
  try { return JSON.parse(fs.readFileSync(p, "utf-8")) as T; }
  catch { return null; }
}

function ensureDir(d: string) {
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
}

function ts() { return new Date().toISOString(); }

// ─── Mind Loader ─────────────────────────────────────────────────────────────

interface MindContext {
  name:      string;
  thinking:  string;
  framework: string;
  phrases:   string;
}

function loadMind(mindId: string, displayName: string): MindContext {
  const base = path.join(MINDS_DIR, mindId);
  return {
    name:      displayName,
    thinking:  readText(path.join(base, "sources",   "thinking_dna.yaml")).slice(0, 1200),
    framework: readText(path.join(base, "artifacts", "framework-primary.md")).slice(0, 1500),
    phrases:   readText(path.join(base, "artifacts", "signature-phrases.md")).slice(0, 600),
  };
}

// ─── Prompt Builder ───────────────────────────────────────────────────────────

function buildReviewPrompt(minds: MindContext[], actionsJson: string): string {
  const mindsBlock = minds.map((m) => `
### ${m.name}

**Thinking DNA (excerpt):**
${m.thinking}

**Primary Framework (excerpt):**
${m.framework}

**Signature Phrases:**
${m.phrases}
`).join("\n---\n");

  return `
You are the Department of Strategy of One Agent Corp — Swarm OS v4.2.

You have THREE strategic advisors reviewing an action plan generated by the Department of Flow Intelligence.
Each advisor must vote independently using THEIR OWN FRAMEWORK.

${mindsBlock}

---

## Action Plan to Review (JSON)

${actionsJson}

---

## Your Task

Each advisor must:
1. Review every action in the list
2. Vote: "approve", "reject", or "amend"
3. Apply their unique framework lens
4. Provide a brief but sharp rationale (2-3 sentences max)
5. If "amend": rewrite the ACID fields (action/context/indicator/deadline) with improvements

Then produce a CONSENSUS decision:
- "approved"          → all 3 approve, or 2 approve and 1 amends minor details
- "partially_approved" → mixed votes — keep approved/amended actions, discard rejected
- "rejected"          → 2+ advisors reject the overall plan

---

## Output Format

Respond with ONLY the following JSON (no markdown, no explanation outside the JSON):

<<JSON_START>>
{
  "version": "1.0",
  "project": "${PROJECT_ID}",
  "reviewed_at": "${ts()}",
  "status": "approved | partially_approved | rejected",
  "strategy_board": {
    "ray_dalio": {
      "vote": "approve | reject | amend",
      "framework_applied": "name of framework used",
      "rationale": "2-3 sentence rationale using Dalio's voice and Principles lens",
      "amendments": []
    },
    "eliyahu_goldratt": {
      "vote": "approve | reject | amend",
      "framework_applied": "Theory of Constraints — 5 Focusing Steps",
      "rationale": "2-3 sentences using TOC lens — which action attacks the constraint?",
      "amendments": []
    },
    "michael_porter": {
      "vote": "approve | reject | amend",
      "framework_applied": "Five Forces / Value Chain",
      "rationale": "2-3 sentences using Porter's competitive lens",
      "amendments": []
    }
  },
  "consensus": "approved | partially_approved | rejected",
  "board_synthesis": "2-3 sentences synthesizing all three advisors' verdict",
  "critical_constraint": "The ONE action Goldratt identifies as the system constraint to attack first",
  "actions": [
    {
      "id": "action-001",
      "rank": 1,
      "bottleneck": "...",
      "ice_score": 0,
      "type": "sistema",
      "root_cause": "...",
      "status": "approved | rejected | amended",
      "acid": {
        "action": "final action (original or amended)",
        "context": "final context",
        "indicator": "final indicator",
        "deadline": "final deadline"
      },
      "script": "scripts/auto-audit.ts or null",
      "script_args": ["--project=${PROJECT_ID}"],
      "dependencies": [],
      "amendment_reason": "only if status=amended — why it was changed"
    }
  ]
}
<<JSON_END>>

RULES:
- If an action has script: null, keep it as null (it is a manual action)
- The "actions" array must contain ALL actions from the input, each with a status
- Rejected actions keep their data but get status "rejected"
- Amended actions get updated acid fields and amendment_reason
- The order of actions in the output must respect the dependency chain (lower rank = runs first)
- Use Dalio's "Pain + Reflection = Progress" lens, Goldratt's "Find the Constraint" lens, and Porter's "Strategic Position" lens
`.trim();
}

// ─── Claude Session ───────────────────────────────────────────────────────────

let _session: ReturnType<typeof createAgentSession> extends Promise<infer T> ? T : never | null = null as any;

async function getSession() {
  if (_session) return _session;
  const authStorage    = AuthStorage.create();
  const modelRegistry  = new ModelRegistry(authStorage);
  const result = await createAgentSession({
    sessionManager: SessionManager.inMemory(),
    authStorage,
    modelRegistry,
  });
  _session = result;
  return result;
}

async function callClaude(prompt: string): Promise<string> {
  const { session } = await getSession();
  const chunks: string[] = [];

  const unsubscribe = session.subscribe((event: any) => {
    if (
      event.type === "message_update" &&
      event.assistantMessageEvent?.type === "text_delta"
    ) {
      const delta = event.assistantMessageEvent.delta as string;
      process.stdout.write(delta);
      chunks.push(delta);
    }
  });

  try {
    await session.prompt(prompt);
  } finally {
    unsubscribe();
  }

  return chunks.join("");
}

// ─── JSON Extractor ───────────────────────────────────────────────────────────

function extractJson(text: string): string | null {
  // Primary: custom markers
  const marked = text.match(/<<JSON_START>>([\s\S]*?)<<JSON_END>>/);
  if (marked) return marked[1].trim();

  // Fallback 1: markdown code block
  const md = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (md) return md[1].trim();

  // Fallback 2: raw JSON object (first { ... })
  const raw = text.match(/\{[\s\S]*\}/);
  if (raw) return raw[0];

  return null;
}

// ─── Fallback Approval (if Claude fails) ─────────────────────────────────────

function buildFallbackApproval(input: any): any {
  console.log("\n  ⚠️  Usando aprovação fallback (sem chamada Claude)...");
  return {
    version:       "1.0",
    project:       PROJECT_ID,
    reviewed_at:   ts(),
    status:        "approved",
    strategy_board: {
      ray_dalio:        { vote: "approve", framework_applied: "Principles-Based Decision Making", rationale: "Fallback auto-approval: principle 'move fast on clear bottlenecks' applies.", amendments: [] },
      eliyahu_goldratt: { vote: "approve", framework_applied: "Theory of Constraints",           rationale: "Fallback: constraint identified by flow-intelligence is the system bottleneck — attack it first.", amendments: [] },
      michael_porter:   { vote: "approve", framework_applied: "Five Forces / Value Chain",        rationale: "Fallback: operational efficiency improvement aligns with value chain optimization.", amendments: [] },
    },
    consensus:           "approved",
    board_synthesis:     "Auto-approved: all actions address identified bottlenecks directly.",
    critical_constraint: input.summary?.top_bottleneck || "unknown",
    actions: (input.actions || []).map((a: any) => ({
      ...a,
      status: "approved",
      amendment_reason: null,
    })),
  };
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("╔══════════════════════════════════════════════════╗");
  console.log("║   Department of Strategy — Review & Approval     ║");
  console.log("║   Minds: Dalio · Goldratt · Porter               ║");
  console.log("╚══════════════════════════════════════════════════╝");
  console.log(`\n🎯 Projeto: ${PROJECT_ID}`);

  // 1. Ler growth-actions.json
  const actionsPath = path.join(FLOW_DIR, "growth-actions.json");
  if (!fs.existsSync(actionsPath)) {
    console.error(`\n❌ growth-actions.json não encontrado em: ${actionsPath}`);
    console.error("   Execute primeiro: npx tsx scripts/flow-intelligence.ts");
    process.exit(1);
  }

  const inputJson = readJson<any>(actionsPath);
  if (!inputJson) {
    console.error("❌ Erro ao parsear growth-actions.json");
    process.exit(1);
  }

  console.log(`\n  ✓ growth-actions.json carregado`);
  console.log(`  ✓ ${inputJson.actions?.length || 0} ações para revisar`);
  console.log(`  ✓ Top bottleneck: ${inputJson.summary?.top_bottleneck || "N/A"} (ICE: ${inputJson.summary?.top_ice_score || 0})`);

  // 2. Carregar Minds
  console.log("\n📚 [Strategy] Carregando minds do board estratégico...");
  const minds: MindContext[] = [
    loadMind("ray_dalio",        "Ray Dalio"),
    loadMind("eliyahu_goldratt", "Eliyahu Goldratt"),
    loadMind("michael_porter",   "Michael Porter"),
  ];
  minds.forEach((m) => console.log(`  ✓ ${m.name} — framework carregado`));

  // 3. Construir prompt
  const prompt = buildReviewPrompt(minds, JSON.stringify(inputJson, null, 2));
  console.log(`\n  ✓ Prompt construído (${prompt.length} chars)`);

  // 4. Chamar Claude
  let approved: any;
  console.log("\n🤖 [Strategy Board] Revisando plano de ação...\n");
  console.log("─".repeat(60));

  try {
    const rawResponse = await callClaude(prompt);
    console.log("\n" + "─".repeat(60));

    const jsonStr = extractJson(rawResponse);
    if (!jsonStr) throw new Error("Não foi possível extrair JSON da resposta");

    approved = JSON.parse(jsonStr);
    console.log("\n  ✅ Resposta do board parseada com sucesso");
  } catch (err) {
    console.error(`\n  ⚠️  Erro ao processar resposta Claude: ${err}`);
    approved = buildFallbackApproval(inputJson);
  }

  // 5. Escrever approved-actions.json
  ensureDir(FLOW_DIR);
  const approvedPath = path.join(FLOW_DIR, "approved-actions.json");
  fs.writeFileSync(approvedPath, JSON.stringify(approved, null, 2), "utf-8");

  // 6. Sumário
  const approvedCount  = (approved.actions || []).filter((a: any) => a.status === "approved"  || a.status === "amended").length;
  const rejectedCount  = (approved.actions || []).filter((a: any) => a.status === "rejected").length;
  const amendedCount   = (approved.actions || []).filter((a: any) => a.status === "amended").length;

  console.log("\n╔══════════════════════════════════════════════════╗");
  console.log("║   ✅ Strategy Review — Concluído                  ║");
  console.log("╚══════════════════════════════════════════════════╝");
  console.log(`\n  Consensus:     ${approved.consensus?.toUpperCase() || "N/A"}`);
  console.log(`  Aprovadas:     ${approvedCount}`);
  console.log(`  Emendadas:     ${amendedCount}`);
  console.log(`  Rejeitadas:    ${rejectedCount}`);
  console.log(`  Constraint #1: ${approved.critical_constraint || "N/A"}`);
  console.log(`\n  📋 approved-actions.json → ${approvedPath}\n`);

  if (approved.consensus === "rejected") {
    console.error("🚫 Plano rejeitado pelo board de estratégia. Revise o bottleneck-report.md.");
    process.exit(1);
  }
}

main().catch((e) => {
  console.error("❌ Erro no Department of Strategy:", e);
  process.exit(1);
});
